### ISSUE TITLE
Specifics regarding the testing process and the results obtained.

### ISSUE THREAD

**Issue by narendoraiswamy** [lzzcd001/OSLSM#10]
Hello Amirreza,

This is great work implementing one shot learning for semantic segmentation. I see that the results obtained after testing the model on the validation data set of PASCAL gives out soft and hard segmentation masks but the details regarding the testing process is quite not defined in the paper. So how can i interpret the results ? As in how are the support and the query images selected from the testing data to generate the segmentation masks. 

Thank you.

**Comment by haamoon** [comment]
Hi Naren, 

See if this helps: https://github.com/lzzcd001/OSLSM/issues/12

-Amirreza

**Comment by narendoraiswamy** [comment]
Hi,

Thank you. That did solve the issue for me.

Regards
