### ISSUE TITLE
Error of "boost::python::error_already_set"

### ISSUE THREAD

**Issue by ruinianxu** [lzzcd001/OSLSM#20]
Hi all,
I'd like to train OSLSM on voc2012 first and then try it on my own dataset. I got the following error by training on voc2012. Since there is no enough information about error, I'd like to know if you have any ideas about it.
`I0310 17:35:34.713107  9223 layer_factory.hpp:77] Creating layer first_img
I0310 17:35:39.396251  9223 net.cpp:84] Creating Layer first_img
I0310 17:35:39.396296  9223 net.cpp:380] first_img -> first_img
I0310 17:35:39.396324  9223 net.cpp:380] first_img -> second_img
I0310 17:35:39.396344  9223 net.cpp:380] first_img -> first_label
I0310 17:35:39.396358  9223 net.cpp:380] first_img -> second_label
terminate called after throwing an instance of 'boost::python::error_already_set'
*** Aborted at 1552253739 (unix time) try "date -d @1552253739" if you are using GNU date ***
PC: @     0x7fe3fbf86c37 (unknown)
*** SIGABRT (@0x3e800002407) received by PID 9223 (TID 0x7fe3fdf0e7c0) from PID 9223; stack trace: ***
    @     0x7fe3fbf86cb0 (unknown)
    @     0x7fe3fbf86c37 (unknown)
    @     0x7fe3fbf8a028 (unknown)
    @     0x7fe3fc597e63 (unknown)
    @     0x7fe3fc59cfa6 (unknown)
    @     0x7fe3fc59cfe1 (unknown)
    @     0x7fe3fc59d213 (unknown)
    @     0x7fe3eb65ab62 (unknown)
    @     0x7fe3b50d7975 caffe::PythonLayer<>::LayerSetUp()
    @     0x7fe3fd70ccb2 caffe::Net<>::Init()
    @     0x7fe3fd70f275 caffe::Net<>::Net()
    @     0x7fe3fd742e47 caffe::Solver<>::InitTrainNet()
    @     0x7fe3fd744323 caffe::Solver<>::Init()
    @     0x7fe3fd74463f caffe::Solver<>::Solver()
    @     0x7fe3fd728ed1 caffe::Creator_SGDSolver<>()
    @           0x40ad10 train()
    @           0x407aa8 main
    @     0x7fe3fbf71f45 (unknown)
    @           0x408280 (unknown)
`
Thansk in advance for any hints.

**Comment by ruinianxu** [comment]
The error raised when it tried to load annotation txt file for SBD dataset. In the function create_anns under util.py, it loads txt file from dataset according to the path osp.join(self.db_path, 'ImageSets', 'Segmentation', self.dataType + '.txt'). But dataset architectures of SBD and Pascal are different such that it works for Pascal but not for SBD. In the readme, it only mentions that I need to download SBD dataset but it seems author did some post-processing to the SBD dataset. Does anybody know the correct structure of SBD dataset? Thanks in advance.

**Comment by haamoon** [comment]
Hi,

I believe we somehow converted SBD to Pascal VOC format. Unfortunately, I don't have the conversion code anymore. Hopefully, someone has already post it online but implementing it should not require much work since their structure is not very different.

Best,
Amirreza

**Comment by ruinianxu** [comment]
@haamoon Thank you so much for your reply. I have converted the SBD to Pascal and will try to train the model later. Btw, what is the purpose of using two datasets? If I'd like to train on my dataset, do you have any recommendations that I can minimally modify my dataset since I only have one dataset?

**Comment by wangcm12** [comment]
@ruinianxu I have the same problem of you. Do you have the conversion code about SBD ?I'd like to train my dataset, do you solve the problem of one dataset?Thanks!

**Comment by ruinianxu** [comment]
@wangcm12 For the conversion code, it is easy to find it through google if you type in something like convert SDB to VOC. For customized dataset, not yet. I just get the original training code working and have't had enough time to figure out how to do it.
