### ISSUE TITLE
How does the weight hashing comply

### ISSUE THREAD

**Issue by Husband-of-Reimu** [lzzcd001/OSLSM#22]
Hi authors,  
  Thank you for sharing your code. I've read the code and paper, and i'm interested in the weight hashing.  
  I read the "train_ss_os_fc.prototxt" and find that
```
layer {
  name: "rw1s"
  type: "InnerProduct"
  bottom: "fc8f"
  top: "rw1s"
  param {
    lr_mult: 0.0
    decay_mult: 0
  }
  param {
    lr_mult: 0.0
    decay_mult: 0
  }
  inner_product_param {
    num_output: 4096
  }
}
layer {
  name: "rb1s"
  type: "InnerProduct"
  bottom: "fc8f"
  top: "rb1s"
  param {
    lr_mult: 0.0
    decay_mult: 0
  }
  param {
    lr_mult: 0.0
    decay_mult: 0
  }
  inner_product_param {
    num_output: 1
  }
}
```
I reasoned that it was implemented like this. But i'm confused that it used"innerProduct" and you said that using fc layers will bring more parameters and be overfit easily, and the 'rate's are all 0 is strange.  
And i also read the paper **"Compressing Neural Networks with the Hashing Trick"** , but i don't see the code about the formulation.  
Thank you!

**Comment by shray** [comment]
Hi,
Did you see Appendix A? Equations S1-S3 explain how we're able to compute the weight hashing as an inner product layer.
