### ISSUE TITLE
Why are small objects being filtered out?

### ISSUE THREAD

**Issue by SMHendryx** [lzzcd001/OSLSM#23]
Can you explain what the `_remove_small_objects` function is doing? It looks like it's being called during train and test. Images are being downsized by a factor of 32 from 500x500 and then removed if they include less than 3 pixels of the foreground class in the downsized image. Is that correct?

https://github.com/lzzcd001/OSLSM/blob/1e7440cd4e1c1b344a63ed17d7796859755cbf64/OSLSM/code/ss_datalayer.py#L73

**Comment by haamoon** [comment]
Hi SMHendryx,

Yes, I believe that's what the function is doing. I don't remember the details now but it might be a mistake if it is also being called during testing. If that is the case, you also need to do the same in case you want to compare against the results in Table 1 of the paper.

**Comment by SMHendryx** [comment]
Thanks for letting me know @haamoon.
