### ISSUE TITLE
error: unknown layer type:MatMult

### ISSUE THREAD

**Issue by xiaomengyc** [lzzcd001/OSLSM#4]
Hi,

When I am training the model, it goes to the error:
`Check failed: registry.count(type)==1(0 vs. 1) Unknown layer type: MatMult....`

It seems the Caffe does not have the MatMult layer. How did you implement it ?

Thanks!

**Comment by haamoon** [comment]
Hi,

Yes, that is right. MatMult layer is not included in the standard Caffe version. You need to install and use the provided Caffe code for testing/training the model. Follow the steps 1 to 5 to install Caffe. Let me know if you have any other questions.

-Amirreza

**Comment by xiaomengyc** [comment]
Thank you Amirreza!
I recompiled Caffe from this repository. It runs successfully now.

But there is another question.
 The operation **_Weight Hashing_** is implemented by two InnerProduct layers, and the weights of both layers seem to be fixed as their learning rates are 0.  I checked the weights of these two layers after loading the file _os_pretrined.caffemodel_, and found the weights are all 0.  How do these layer map the VGG's output to the right parameters (w, b)?

**Comment by haamoon** [comment]
Thanks for mentioning that. As it is stated in Appendix A in the paper, we use fully connected layers with 0 learning to do the weight hashing. You need to do a little net surgery and set the weights as follows:
```
param_names = ['rw1s', 'rb1s']
for param_name in param_names:
  print 'Initializing', param_names, 'for weight hashing'
  np.random.seed(1348)
  input_size = new_net.params[param_name][0].data.shape[1]
  output_size = new_net.params[param_name][0].data.shape[0]
  inv_hash = np.random.randint(input_size, size = (output_size,))
  signs = 2 * np.random.randint(2, size = (output_size,) ) - 1.0
  new_net.params[param_name][0].data[[range(output_size), inv_hash]] = signs/100.0
  new_net.params[param_name][1].data[...] = 0
```
Let me know if it solves the problem.

Best,
Amirrea

**Comment by xiaomengyc** [comment]
Yes, it exactly solves my problem. Thank you!
