### ISSUE TITLE
How to test with my own images

### ISSUE THREAD

**Issue by DiMorten** [lzzcd001/OSLSM#7]
I'd like to test the pre-trained model with my own set of support and query images. What would be the most straightforward way to do it?

**Comment by haamoon** [comment]
Hi DiMorten,

The dataset reading happens in [DBInterface](https://github.com/lzzcd001/OSLSM/blob/1e7440cd4e1c1b344a63ed17d7796859755cbf64/OSLSM/code/ss_datalayer.py#L21) class. You could either add some code to read your own data in [load_items](https://github.com/lzzcd001/OSLSM/blob/1e7440cd4e1c1b344a63ed17d7796859755cbf64/OSLSM/code/ss_datalayer.py#L81) function or convert your dataset into PASCAL format which is supported by the current implementation. I think converting the data would be more straightforward.

-Amirreza
