### ISSUE TITLE
How do I find the confidence score outputted by the neural net?

### ISSUE THREAD

**Issue by joannetruong** [lzzcd001/OSLSM#8]
How can we find out how trustworthy the inference the net generates is?

**Comment by haamoon** [comment]
Hi,

The network outputs the confidence scores [here](https://github.com/lzzcd001/OSLSM/blob/1e7440cd4e1c1b344a63ed17d7796859755cbf64/OSLSM/os_semantic_segmentation/test.py#L141).

**Comment by joannetruong** [comment]
That returns the output mask, not a confidence score of the mask. The next line calculates the TP/TN/FP/FN based on the overlap of the masks, but that requires that we also pass in a mask for our second image. Since it should be testing on an image that it has no prior knowledge of, there is no corresponding mask for this image, and thus IoU is always 0.

**Comment by haamoon** [comment]
Sorry it looks I couldn't understand the question and I am not sure if I still understand it well. 

The measure(.,.) function receives the prediction for the second_img "net.blobs['score'].data[0,0]" and the ground-truth "second_label[0,0]" label to compute the TP/TN/FP/FN. 

"That returns the output mask, not a confidence score of the mask"
Yes, they are scores (although they are sometimes refer as confidences) not the confidence of each score as we don't need the confidence to be able to compute the binary prediction. We simply threshold the prediction values to generate the binary mask.
